version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "delegation-sequencing/backend"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "delegation-sequencing/frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
